# Generated by Django 6.0.3 on 2026-03-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParkingLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="停车场名称",
                        max_length=128,
                        verbose_name="停车场名称",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_comment="地址",
                        default="",
                        max_length=255,
                        verbose_name="地址",
                    ),
                ),
                (
                    "total_spaces",
                    models.IntegerField(
                        db_comment="总车位数", default=0, verbose_name="总车位数"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="描述"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "停车场",
                "verbose_name_plural": "停车场",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="摄像头名称")),
                (
                    "stream_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="视频流地址（RTSP/文件路径）",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "在线"), ("offline", "离线")],
                        default="offline",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "alert_zones",
                    models.JSONField(
                        blank=True, null=True, verbose_name="警戒区域配置"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cameras",
                        to="parking.parkinglot",
                        verbose_name="所属停车场",
                    ),
                ),
            ],
            options={
                "verbose_name": "摄像头",
                "verbose_name_plural": "摄像头",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="BillingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        default="car", max_length=32, verbose_name="适用车型"
                    ),
                ),
                (
                    "free_minutes",
                    models.IntegerField(default=15, verbose_name="免费时长（分钟）"),
                ),
                (
                    "rate_per_hour",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=6,
                        verbose_name="每小时费率（元）",
                    ),
                ),
                (
                    "daily_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        max_digits=8,
                        verbose_name="日封顶费用（元）",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_rules",
                        to="parking.parkinglot",
                        verbose_name="所属停车场",
                    ),
                ),
            ],
            options={
                "verbose_name": "计费规则",
                "verbose_name_plural": "计费规则",
                "ordering": ["lot", "vehicle_type"],
            },
        ),
        migrations.CreateModel(
            name="ParkingSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "space_no",
                    models.CharField(
                        db_comment="车位编号（如 A-01）",
                        max_length=32,
                        verbose_name="车位编号",
                    ),
                ),
                (
                    "space_type",
                    models.CharField(
                        choices=[
                            ("small", "小型车"),
                            ("large", "大型车"),
                            ("disabled_person", "无障碍"),
                        ],
                        default="small",
                        max_length=32,
                        verbose_name="车位类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "空闲"),
                            ("occupied", "占用"),
                            ("disabled", "禁用"),
                        ],
                        default="available",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(blank=True, null=True, verbose_name="坐标区域"),
                ),
                (
                    "occupied_since",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="占用开始时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spaces",
                        to="parking.camera",
                        verbose_name="关联摄像头",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spaces",
                        to="parking.parkinglot",
                        verbose_name="所属停车场",
                    ),
                ),
            ],
            options={
                "verbose_name": "车位",
                "verbose_name_plural": "车位",
                "ordering": ["lot", "space_no"],
                "unique_together": {("lot", "space_no")},
            },
        ),
        migrations.CreateModel(
            name="VehicleRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "track_id",
                    models.IntegerField(
                        blank=True,
                        db_comment="DeepSORT分配的唯一ID",
                        null=True,
                        verbose_name="跟踪ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="车牌号"
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("car", "小型车"),
                            ("truck", "货车"),
                            ("bus", "大型车/公交"),
                            ("motorcycle", "摩托车"),
                        ],
                        default="car",
                        max_length=32,
                        verbose_name="车辆类型",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("entry", "入场"), ("exit", "出场")],
                        max_length=8,
                        verbose_name="方向",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(default=0.0, verbose_name="识别置信度"),
                ),
                (
                    "snapshot",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="parking/snapshots/%Y/%m/%d/",
                        verbose_name="截图",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_records",
                        to="parking.camera",
                        verbose_name="摄像头",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_records",
                        to="parking.parkinglot",
                        verbose_name="停车场",
                    ),
                ),
            ],
            options={
                "verbose_name": "车辆进出记录",
                "verbose_name_plural": "车辆进出记录",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ParkingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="车牌号"
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        default="car", max_length=32, verbose_name="车辆类型"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "停车中"), ("completed", "已离场")],
                        default="active",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("entry_time", models.DateTimeField(verbose_name="入场时间")),
                (
                    "exit_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="离场时间"
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(default=0, verbose_name="停车时长（分钟）"),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="费用（元）",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="是否已缴费"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="parking.parkinglot",
                        verbose_name="停车场",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="parking.parkingspace",
                        verbose_name="车位",
                    ),
                ),
                (
                    "entry_record",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_as_entry",
                        to="parking.vehiclerecord",
                        verbose_name="入场记录",
                    ),
                ),
                (
                    "exit_record",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_as_exit",
                        to="parking.vehiclerecord",
                        verbose_name="出场记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "停车会话",
                "verbose_name_plural": "停车会话",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ViolationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "track_id",
                    models.IntegerField(blank=True, null=True, verbose_name="跟踪ID"),
                ),
                (
                    "license_plate",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="车牌号"
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("fire_lane", "占用消防通道"),
                            ("no_parking", "禁停区停车"),
                            ("double_park", "双排停车"),
                        ],
                        default="fire_lane",
                        max_length=32,
                        verbose_name="违规类型",
                    ),
                ),
                (
                    "zone_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="违规区域名称",
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(default=0, verbose_name="驻留秒数"),
                ),
                (
                    "snapshot",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="parking/violations/%Y/%m/%d/",
                        verbose_name="违规截图",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待处理"), ("resolved", "已处理")],
                        default="pending",
                        max_length=16,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="处理备注"
                    ),
                ),
                ("violated_at", models.DateTimeField(verbose_name="违规时间")),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="violations",
                        to="parking.camera",
                        verbose_name="触发摄像头",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="violations",
                        to="parking.parkinglot",
                        verbose_name="停车场",
                    ),
                ),
            ],
            options={
                "verbose_name": "违规记录",
                "verbose_name_plural": "违规记录",
                "ordering": ["-id"],
            },
        ),
    ]
