from django.urls import path

from django_utils.views import (
    AdminArticleDetailView,
    AdminArticleListView,
    AdminCategoryDetailView,
    AdminCategoryListView,
    AdminFileDeleteView,
    AdminFileListView,
    ArticleCommentListView,
    ArticlePublicCategoryListView,
    FileDownloadView,
    FileDetailView,
    FileListView,
    FileUploadView,
    AdminLogDeleteView,
    AdminLogListView,
    AdminLogClearView,
    ArticleFavoriteToggleView,
    ArticleLikeToggleView,
    ArticlePublicDetailView,
    ArticlePublicListView,
    MeFavoriteArticlesView,
)

urlpatterns = [
    path("files/upload/", FileUploadView.as_view()),
    path("files/list/", FileListView.as_view()),
    path("files/<int:file_id>/download/", FileDownloadView.as_view()),
    path("files/<int:file_id>/", FileDetailView.as_view()),
    path("admin/files/list/", AdminFileListView.as_view()),
    path("admin/files/<int:file_id>/", AdminFileDeleteView.as_view()),
    path("admin/logs/list/", AdminLogListView.as_view()),
    path("admin/logs/<int:log_id>/", AdminLogDeleteView.as_view()),
    path("admin/logs/clear/", AdminLogClearView.as_view()),
    path("admin/article-categories/list/", AdminCategoryListView.as_view()),
    path("admin/article-categories/<int:category_id>/", AdminCategoryDetailView.as_view()),
    path("admin/articles/list/", AdminArticleListView.as_view()),
    path("admin/articles/<int:article_id>/", AdminArticleDetailView.as_view()),
    path("articles/list/", ArticlePublicListView.as_view()),
    path("articles/categories/list/", ArticlePublicCategoryListView.as_view()),
    path("articles/<int:article_id>/", ArticlePublicDetailView.as_view()),
    path("articles/<int:article_id>/comments/", ArticleCommentListView.as_view()),
    path("articles/<int:article_id>/like/", ArticleLikeToggleView.as_view()),
    path("articles/<int:article_id>/favorite/", ArticleFavoriteToggleView.as_view()),
    path("me/favorite-articles/list/", MeFavoriteArticlesView.as_view()),
]
