# Generated by Django 5.2 on 2026-02-13 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_utils", "0003_alter_operationlog_ip"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="文章分类名称（唯一）",
                        max_length=64,
                        unique=True,
                        verbose_name="分类名称",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="分类说明",
                        default="",
                        max_length=255,
                        verbose_name="分类描述",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_comment="数字越小越靠前", default=0, verbose_name="排序"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="是否在用户端展示",
                        default=True,
                        verbose_name="是否启用",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "文章分类",
                "verbose_name_plural": "文章分类",
                "ordering": ["sort_order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover",
                    models.FileField(
                        blank=True,
                        db_comment="封面文件（使用 FileField 避免依赖 Pillow）",
                        null=True,
                        upload_to="articles/covers/%Y/%m/%d/",
                        verbose_name="封面",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="文章标题", max_length=200, verbose_name="标题"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        db_comment="文章摘要（可选）",
                        default="",
                        max_length=500,
                        verbose_name="摘要",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        db_comment="文章正文内容",
                        default="",
                        verbose_name="内容",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("archived", "已归档"),
                        ],
                        db_comment="草稿/发布/归档",
                        default="draft",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="发布时刻（仅发布状态有效）",
                        null=True,
                        verbose_name="发布时间",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        db_comment="文章浏览次数（可选统计）",
                        default=0,
                        verbose_name="浏览数",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        db_comment="文章作者（管理员编辑时可为空）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_comment="文章分类",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="django_utils.articlecategory",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ArticleComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(db_comment="评论正文", verbose_name="评论内容"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="软删除标记（用户端不展示）",
                        default=False,
                        verbose_name="是否删除",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="评论创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="评论更新时间",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        db_comment="评论所属文章",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="django_utils.article",
                        verbose_name="文章",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_comment="回复目标评论（可为空）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="django_utils.articlecomment",
                        verbose_name="父评论",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_comment="发表评论的用户（允许匿名为空）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="article_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评论用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章评论",
                "verbose_name_plural": "文章评论",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ArticleFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="收藏时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        db_comment="收藏所属文章",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="django_utils.article",
                        verbose_name="文章",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="收藏的用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="收藏用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章收藏",
                "verbose_name_plural": "文章收藏",
                "ordering": ["-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "user"), name="uniq_article_favorite"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ArticleLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="点赞时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        db_comment="点赞所属文章",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="django_utils.article",
                        verbose_name="文章",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="点赞的用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="点赞用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章点赞",
                "verbose_name_plural": "文章点赞",
                "ordering": ["-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "user"), name="uniq_article_like"
                    )
                ],
            },
        ),
    ]
