# Generated by Django 5.2 on 2026-03-29 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_utils", "0004_articlecategory_article_articlecomment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operationlog",
            options={
                "ordering": ["-id"],
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
            },
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="action",
            field=models.CharField(
                blank=True,
                db_comment="动作标识（如 file_upload / admin_user_create）",
                default="",
                max_length=64,
                verbose_name="动作",
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="日志创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="detail",
            field=models.TextField(
                blank=True,
                db_comment="异常信息或补充说明",
                default="",
                verbose_name="详情",
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="ip",
            field=models.CharField(
                blank=True,
                db_comment="客户端 IP（优先 X-Forwarded-For）",
                max_length=64,
                null=True,
                verbose_name="客户端IP",
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="method",
            field=models.CharField(
                blank=True,
                db_comment="HTTP 方法",
                default="",
                max_length=10,
                verbose_name="请求方法",
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                db_comment="触发本次操作的用户",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operation_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作用户",
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="path",
            field=models.CharField(
                blank=True,
                db_comment="HTTP 请求路径",
                default="",
                max_length=255,
                verbose_name="请求路径",
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="remark",
            field=models.CharField(
                blank=True,
                db_comment="便于运营/排查的中文备注",
                default="",
                max_length=255,
                verbose_name="中文备注",
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="response_code",
            field=models.IntegerField(
                blank=True,
                db_comment="统一返回结构中的 code（如 20001）",
                null=True,
                verbose_name="业务码",
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="status_code",
            field=models.IntegerField(
                blank=True,
                db_comment="HTTP 响应状态码",
                null=True,
                verbose_name="HTTP状态码",
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="success",
            field=models.BooleanField(
                db_comment="根据 HTTP 状态码与业务码推断",
                default=True,
                verbose_name="是否成功",
            ),
        ),
    ]
